AWSTemplateFormatVersion: '2010-09-09'
Description: Custom Listener Certificate Provider CloudFormation
Parameters:
  ListenerArn:
    Type: String
  CertificateArn:
    Type: String
Resources:
  Custom:
    Type: Custom::ListenerCertificate
    Properties:
      ListenerArn: !Ref ListenerArn
      CertificateArn: !Ref CertificateArn
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-listener-certificate-provider'
